### ISSUE TITLE
pdtypes fails to import with pandas 2.2.0

### ISSUE THREAD

**Issue by jiemakel** [pwwang/pdtypes#2]
importing `pdtypes` fails with `ImportError: cannot import name 'GenericArrayFormatter' from 'pandas.io.formats.format'` due to 
https://github.com/pandas-dev/pandas/commit/6c58a217f5d9a2520d9d4bee665edff5397bbfc6 changing `GenericArrayFormatter` to `_GenericArrayFormatter` (amongst other similar changes)

**Comment by pwwang** [comment]
Fixed by [v0.2.1](https://github.com/pwwang/pdtypes/releases/tag/0.2.1).
